const express = require('express');
const { Client, RichEmbed } = require('discord.js');
const app = express();
    function sleep(milliseconds) {
  var start = new Date().getTime();
  for (var i = 0; i < 1e7; i++) {
    if ((new Date().getTime() - start) > milliseconds){
      break;
    }
  }
}
const http = require('http');
app.get("/", (request, response) => {
    response.sendStatus(200);
    });
    app.listen(process.env.PORT);
    setInterval(() => {
    http.get('http://boost-aktif.glitch.me/');
    }, 3000);
const Discord = require('discord.js');
const client = new Discord.Client();
const data = new Map();

const scream = new Discord.Client();
const scream1 = new Discord.Client();
const scream2 = new Discord.Client();
const scream3 = new Discord.Client();
const scream4 = new Discord.Client();
const scream5 = new Discord.Client();
const scream6 = new Discord.Client();
const scream7 = new Discord.Client();
const scream8 = new Discord.Client();
const scream9 = new Discord.Client();
const scream10 = new Discord.Client();
const scream11 = new Discord.Client();
const scream12 = new Discord.Client();
const scream13 = new Discord.Client();
const scream14 = new Discord.Client();
const scream15 = new Discord.Client();
const scream16 = new Discord.Client();
const scream17 = new Discord.Client();
const scream18 = new Discord.Client();
const scream19 = new Discord.Client();
const scream20 = new Discord.Client();
const scream21 = new Discord.Client();
const scream22 = new Discord.Client();
const scream23 = new Discord.Client();
const scream24 = new Discord.Client();
const scream25 = new Discord.Client();
const scream26 = new Discord.Client();
const scream27 = new Discord.Client();
const scream28 = new Discord.Client();
const scream29 = new Discord.Client();
const scream30 = new Discord.Client();
const scream31 = new Discord.Client();
const scream32 = new Discord.Client();
const scream33 = new Discord.Client();
const scream34 = new Discord.Client();
const scream35 = new Discord.Client();
const scream36 = new Discord.Client();
const scream37 = new Discord.Client();
const scream38 = new Discord.Client();
const scream39 = new Discord.Client();
const scream40 = new Discord.Client();
const scream41 = new Discord.Client();
const scream42 = new Discord.Client();
const scream43 = new Discord.Client();
const scream44 = new Discord.Client();
const scream45 = new Discord.Client();
const scream46 = new Discord.Client();
const scream47 = new Discord.Client();
const scream48 = new Discord.Client();
const scream49 = new Discord.Client();
const scream50 = new Discord.Client();
const scream51 = new Discord.Client();
const scream52 = new Discord.Client();
const scream53 = new Discord.Client();
const scream54 = new Discord.Client();
const scream55 = new Discord.Client();
const scream56 = new Discord.Client();
const scream57 = new Discord.Client();
const scream58 = new Discord.Client();
const scream59 = new Discord.Client();
const scream60 = new Discord.Client();
const scream61 = new Discord.Client();
const scream62 = new Discord.Client();
const scream63 = new Discord.Client();
const scream64 = new Discord.Client();
const scream65 = new Discord.Client();


scream1.login("Nzk4OTE1MzE0MzM5MTUxOTEz.X_7_UQ.9BFjHnEYs9ibIYW1LhoTAD6Kzjs");
scream2.login("Nzk4OTE3NDc0NzMyMzQzMzM2.X_7__w.Sr6IHpjOVvLSTgUYdT_5yTvxTnA");
scream3.login("Nzk4OTE3NzcxMTg5NTUxMTA1.X_8Apw.dz__Rt1zJ7yQsdK7T9ZlgjzQEaQ");
scream4.login("Nzk4OTE4NTQ1NzY5MjM0NDM1.X_8A-A.6r6CCRXd5ZFhHg8XMwGaeiX8Fb8");
scream5.login("Nzk4OTE4NzgwNjk2Nzg5MDIy.X_8BPQ.K9reap9ttZqhfTMHKZHaaeajTys");
scream6.login("Nzk4OTE5MTI2NDgyNjgxODc3.X_8BiA.XZmExoNd7aZHxC_fLXZwjcgUXcw");
scream7.login("Nzk4OTE5NDIxMjc5ODYyODI1.X_8B1Q.5XVj9dt6lpdaHUFXVMHU5fc0C_w");
scream8.login("Nzk4OTE5NzM4ODYzOTEwOTYz.X_8CFg.qH4cs6Fcvtx5RMnprsGyPzP2pg8");
scream9.login("Nzk3NDE0MTI1MzgyNTMzMTIw.X_7hmA.JT8JzrD0OYXGMQDJSVuZ1eXA-b0");
scream10.login("Nzk4OTE5OTg3MjI5NDkxMjMx.X_8CsQ.eZNNzp5ap1d-wA6W5d2-nYulmBg");
scream11.login("Nzk4OTIwNjUwNjgwNDM0NzI5.X_8C9g.NibtRNBG9_lFGGzL8i_z44TVc8U");
scream12.login("Nzk4OTIwOTQ2MzI0NzM0MDM0.X_8DTA.X2AIQxsvLtoadRQvj7dd-ieFa2o");
scream13.login("Nzk4OTIxMzQzMzcwMTMzNTg0.X_8Dkg.YbG7heUJ1YlCEwT--DoUesKmGRA");
scream14.login("Nzk4OTIxNTk3ODgzNzc3MDc0.X_8D4g.vs93ZnJRnVhmju0P0ZxU8Lyrzj8");
scream15.login("Nzk4OTIxOTM4ODY0NzAxNDQw.X_8ELA.ifgvdR72MrUCIFe9rI3RvuJEsko");
scream16.login("Nzk4OTIyMjMwODkzMzc5NjM1.X_8Ecg.VucT7p8snCDoedJi9Tmo2Zu3hyQ");
scream17.login("Nzk4OTIyNjAwNDg2MTQxOTY0.X_8E1Q.SEx59qVzcTLbBcJCg6KujJwiQZI");
scream18.login("Nzk4OTIzMDU0MzY4ODE3MjAy.X_8FMg.vkUnWUtJy9POlseTogKQNVnvq_s");
scream19.login("Nzk4OTIzMzY3MjY4MjIwOTY4.X_8FiA.e8rCLeW-1gNbo8ga6SJLHR-leKw");
scream20.login("Nzk4OTIzNzIzMzA2MDQxMzQ1.X_8F6Q.rY3eplyu4ZhoeErNSMsrJ5HpI5I");
scream21.login("Nzk5MjU2NDcwMjIyMTQzNTI4.YAA7lw.yTpfoutqJddvJ5q9vDL5V2yNpmo");
scream22.login("Nzk5MjU2NjIzMzM5NjY3NDU2.YAA7vA.7n6Iqil41zu-pcn1FwA4UJ6R1WU");
scream23.login("Nzk5MjU3MDA1MDA5MTQxODAw.YAA8Fw.KOMfmMcftw-XcCEKdAym9oH8zoY");
scream24.login("Nzk5MDE0NjY3Nzc0NzIyMTE4.X_9aZQ.3F3gk87faqed1Wm_DDqE3ovQyqw");
scream25.login("Nzk5MDIxMTM0MzM0MDAxMTU0.X_9gaw.0T1aiWSGw2Rg9rtXgx-SMeXQMVE");
scream26.login("ODAxMDY0NzI1MjkwNTQ5MjY5.YAbQAA.ZQBkj3S1qPRCitqi1bNrdSz_2Y4");
scream27.login("ODAxMDY1MjkzMTk0OTg1NTEz.YAbQZA.beeZQNVvPxE-H9d61NZ0GvBpiJ8");
scream28.login("ODAxMDY1Nzc4ODAzNjM4MzIy.YAbQ0Q.SBbt7yvh2dXi7lhyVelk8AIzJIA");
scream29.login("ODAxMDY2MTMwMTMxMTI0MjM0.YAbRFQ.upyEQvUDzCA2cs_gH7uhIjmynAE");
scream30.login("ODAxMDY2MzkyMDg1NzI1MjI3.YAbRew.dzdXZGMfk7Yq5dTgU6ExVEXVxys");
scream31.login("ODAxMDY2ODEzMzc0NTk1MTEy.YAbRrg.HoUgIgycuadOkrPpAsbGckHbDNQ");
scream32.login("ODAxMDY3MTAzNTExMTE3ODM0.YAbSPQ.cvENXX33kLk6zHAatEHwYR6t2tA");
scream33.login("ODAxMDY3Nzc4OTM2MTQzODcy.YAbSsQ.nZ25_DViHfDrOijZnftazqNtyeU");
scream34.login("ODAxMDY4MjIxNzk2OTc0NjUy.YAbTOg.noRfwSkcYn_mPPh1rLuscmZClzQ");
scream35.login("ODAxMDY4ODY5NTA2NDMzMDM0.YAbTmw.xLVVFNzcgbkFxI3uPc_Q0BHDnJg");
scream36.login("ODAxMDY5NTIzNTA3NDc4NTI4.YAbUTw.rEOt3GJHiuoJp3hZ3Khzns1B47U");
scream37.login("ODAxMDY5ODg3MjYyNjg3MjQy.YAbUjw.RXERr6YDFnRB6EPpsreVsqI7ZIM");
scream38.login("ODAxMDcwMTMzNjc3NTIyOTQ1.YAbUyg.R3QACSnVaCBCX7dKiT_p0efXPZU");
scream39.login("ODAxMDcwMzI5Nzk5NjM5MDYw.YAbVKA.jv2stLzNHK6XPZQ850PF820ii10");
scream40.login("ODAxMDcwODMxNTIxNDk3MDg5.YAbVag.NezwXwuPFkvEReoDFdPPSz9R5fM");
scream41.login("ODAxMDcxMDY2NDY5MzY3ODE5.YAbVwA.ZRZ3FOZRFyhgMJotX6bCijYuhiA");
scream42.login("ODAxMDcxNDc5MDMwNDE1MzYw.YAbWBA.2rYusRv0Wsa69slwjuMkQDmvFGs");
scream43.login("ODAxMDcxNzYzNjMwODUwMDQ4.YAbWWw.uOxkaQeYYrfmL43asFb7KG8ugTU");
scream44.login("ODAxMDcyMDg0MTYzNDkzOTI4.YAbWlw.K7SoQ-OT_F9BSxDohV1sCoKhKJE");
scream45.login("ODAxMDcyMzE1ODE4MzExNzEw.YAbW9w.0DZaGET0ZM9qXGzFa9vNuMVuoFM");
scream45.login("ODAzNjIyMjg2NDY4MDU1MDYw.YBAeUw.H1OaUiEPKV4QLhewUr1-Az_Z0zA");
scream46.login("ODAzNjIzNDM1ODg0MTY3MTk5.YBAeuQ._jtP6w2ePWULy6bSS5zMZtVNoFo");
scream47.login("ODAzNjIzODc0MTIyMDg4NDQ5.YBAfJg.q5Qg16D7T-ysVeAigYPJEnlCnQs");
scream48.login("ODAzNjI0MjIxMDUzODEyNzg3.YBAfdQ.PpbWPS22cchPy3Rl1T7AcU-d-tQ");
scream49.login("ODAzNjI0ODI3NTQxOTEzNjUw.YBAgDQ.9tdmwCtXdNpDBw2cYCcL-A2Py3Y");
scream50.login("ODAzNjI1MjY0NTI5NDA4MDEw.YBAgbg.3NdhaKV8Uz2bewUodXgYyap2-A8");
scream51.login("ODAzNjI1NzUyNjc1MjIxNTc1.YBAg-A.s7vcDauZWa9nWwSjx1g0EqR_0qQ");
scream52.login("ODAzNjI2MTE0MTczMzcwNDM5.YBAhOw.qw8D-FyOZPy4YmofPNc-uit2YWs");
scream53.login("ODAzNjI2NDYyMzAxMjU3NzQ4.YBAiAQ.1Ad8fDjHUt28ZiGWkFAwawSVk-w");
scream54.login("ODAzNjI3MjMwODg1NDQ1Njky.YBAiRg.INtE4kRrmf94MbpTGX3rZ4g23sE");
scream55.login("ODAzNjI3NTkwMDc3MTIwNjAz.YBAikg.SnmhXOWDygR7ibe7RqxC0A9OOp8");
scream56.login("ODAzNjI3ODM4NDU1NDE0Nzk2.YBAi0A.UO5pWRCiNGq42Krd4IPtFClaG3s");
scream57.login("ODAzNjI4MTI4ODgxOTk5ODky.YBAjJA.R9_SQpIp-J_wp6j9z1Y7qHQTxiQ");
scream58.login("ODAzNjI4NzQ0MDI3NDA2MzQ3.YBAjqg.BsYOKbkePE4PYCA035KOaD7yBGw");
scream59.login("ODAzNjI4OTkxMjY0NDU2Nzc5.YBAj4Q.jxIhZv3P9dGAQfT25oNXD53Hrv4");
scream60.login("ODAzNjI5MjE1OTc4MDk0NTky.YBAkTg.EGObG9exr7uf7HSCqZmCfIhpfQ8");
scream61.login("ODAzNjI5Nzg4MTU2OTE5ODI5.YBAkqQ.oB-HM2LQb1jL76_MJY4dBJTAw90");
scream62.login("ODAzNjMwMDE0NDYxMzc4NjA1.YBAk8Q.cZGOTR7JA6u8NgjTlubp5tVmLow");
scream63.login("ODAzNjMwOTM3ODQwNTQ5OTIw.YBAlvA.w83SCjzmXy9Yzwpm5mgOIW8Qkro");
scream64.login("ODAzNjMxMjQzNjUyMzY2Mzg4.YBAmFQ.w2YJQkzNQQr5oSBM66D5lTCQPJE");
scream65.login("ODAzNjMxNjg3NjI3MDQ2OTUy.YBAmbQ.-FYXWx3iGys5h9Sh4LNPYAbhec4");